# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'domain_learning.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DomainLearningWindow(object):
    def setupUi(self, DomainLearningWindow):
        DomainLearningWindow.setObjectName("DomainLearningWindow")
        DomainLearningWindow.resize(971, 800)
        self.centralWidget = QtWidgets.QWidget(DomainLearningWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_1 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.scenes_list = QtWidgets.QListView(self.frame_1)
        self.scenes_list.setObjectName("scenes_list")
        self.verticalLayout_2.addWidget(self.scenes_list)
        self.track_objects_checkbox = QtWidgets.QCheckBox(self.frame_1)
        self.track_objects_checkbox.setObjectName("track_objects_checkbox")
        self.verticalLayout_2.addWidget(self.track_objects_checkbox)
        self.calibrate_btn = QtWidgets.QPushButton(self.frame_1)
        self.calibrate_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.calibrate_btn.setObjectName("calibrate_btn")
        self.verticalLayout_2.addWidget(self.calibrate_btn)
        self.init_scene_size_btn = QtWidgets.QPushButton(self.frame_1)
        self.init_scene_size_btn.setObjectName("init_scene_size_btn")
        self.verticalLayout_2.addWidget(self.init_scene_size_btn)
        self.line = QtWidgets.QFrame(self.frame_1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.project_name_le = QtWidgets.QLineEdit(self.frame_1)
        self.project_name_le.setObjectName("project_name_le")
        self.verticalLayout_2.addWidget(self.project_name_le)
        self.load_proj_btn = QtWidgets.QPushButton(self.frame_1)
        self.load_proj_btn.setObjectName("load_proj_btn")
        self.verticalLayout_2.addWidget(self.load_proj_btn)
        self.horizontalLayout.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(90)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(800, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instructions_label = QtWidgets.QLabel(self.frame_2)
        self.instructions_label.setWordWrap(True)
        self.instructions_label.setObjectName("instructions_label")
        self.verticalLayout.addWidget(self.instructions_label)
        self.horizontalLayout.addWidget(self.frame_2)
        DomainLearningWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(DomainLearningWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 971, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEvents_and_Actions = QtWidgets.QMenu(self.menuBar)
        self.menuEvents_and_Actions.setObjectName("menuEvents_and_Actions")
        DomainLearningWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(DomainLearningWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        DomainLearningWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(DomainLearningWindow)
        self.statusBar.setObjectName("statusBar")
        DomainLearningWindow.setStatusBar(self.statusBar)
        self.actionCreate_Project = QtWidgets.QAction(DomainLearningWindow)
        self.actionCreate_Project.setObjectName("actionCreate_Project")
        self.actionLoad_Project = QtWidgets.QAction(DomainLearningWindow)
        self.actionLoad_Project.setObjectName("actionLoad_Project")
        self.actionSave_Project = QtWidgets.QAction(DomainLearningWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionEvents = QtWidgets.QAction(DomainLearningWindow)
        self.actionEvents.setObjectName("actionEvents")
        self.actionActions = QtWidgets.QAction(DomainLearningWindow)
        self.actionActions.setObjectName("actionActions")
        self.actionRules = QtWidgets.QAction(DomainLearningWindow)
        self.actionRules.setObjectName("actionRules")
        self.menuFile.addAction(self.actionCreate_Project)
        self.menuFile.addAction(self.actionLoad_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuEvents_and_Actions.addAction(self.actionEvents)
        self.menuEvents_and_Actions.addAction(self.actionActions)
        self.menuEvents_and_Actions.addAction(self.actionRules)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEvents_and_Actions.menuAction())

        self.retranslateUi(DomainLearningWindow)
        QtCore.QMetaObject.connectSlotsByName(DomainLearningWindow)

    def retranslateUi(self, DomainLearningWindow):
        _translate = QtCore.QCoreApplication.translate
        DomainLearningWindow.setWindowTitle(_translate("DomainLearningWindow", "DomainLearningWindow"))
        self.label_2.setText(_translate("DomainLearningWindow", "Scenes"))
        self.track_objects_checkbox.setText(_translate("DomainLearningWindow", "Track Objects"))
        self.calibrate_btn.setText(_translate("DomainLearningWindow", "Calibrate Projector"))
        self.init_scene_size_btn.setText(_translate("DomainLearningWindow", "Init Scene Size"))
        self.project_name_le.setText(_translate("DomainLearningWindow", "[project_name]"))
        self.load_proj_btn.setText(_translate("DomainLearningWindow", "Load..."))
        self.instructions_label.setText(_translate("DomainLearningWindow", "Instructions ... / Status ... "))
        self.menuFile.setTitle(_translate("DomainLearningWindow", "File"))
        self.menuEvents_and_Actions.setTitle(_translate("DomainLearningWindow", "Events and Actions"))
        self.actionCreate_Project.setText(_translate("DomainLearningWindow", "Create Project ..."))
        self.actionLoad_Project.setText(_translate("DomainLearningWindow", "Load Project ..."))
        self.actionSave_Project.setText(_translate("DomainLearningWindow", "Save Project ..."))
        self.actionEvents.setText(_translate("DomainLearningWindow", "Events ..."))
        self.actionActions.setText(_translate("DomainLearningWindow", "Actions ..."))
        self.actionRules.setText(_translate("DomainLearningWindow", "Rules ..."))
