# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handskill_exercise_execution.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(286, 327)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_calibrate_projector = QtWidgets.QPushButton(self.centralwidget)
        self.button_calibrate_projector.setObjectName("button_calibrate_projector")
        self.horizontalLayout_3.addWidget(self.button_calibrate_projector)
        self.button_init_scene_size = QtWidgets.QPushButton(self.centralwidget)
        self.button_init_scene_size.setObjectName("button_init_scene_size")
        self.horizontalLayout_3.addWidget(self.button_init_scene_size)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 3)
        self.label_exercise_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_exercise_2.setObjectName("label_exercise_2")
        self.gridLayout.addWidget(self.label_exercise_2, 1, 0, 1, 1)
        self.exercise_typ_box = QtWidgets.QGroupBox(self.centralwidget)
        self.exercise_typ_box.setObjectName("exercise_typ_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.exercise_typ_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_button_follow = QtWidgets.QRadioButton(self.exercise_typ_box)
        self.radio_button_follow.setObjectName("radio_button_follow")
        self.horizontalLayout.addWidget(self.radio_button_follow)
        self.radio_button_catch = QtWidgets.QRadioButton(self.exercise_typ_box)
        self.radio_button_catch.setObjectName("radio_button_catch")
        self.horizontalLayout.addWidget(self.radio_button_catch)
        self.gridLayout.addWidget(self.exercise_typ_box, 1, 1, 1, 2)
        self.label_project_name = QtWidgets.QLabel(self.centralwidget)
        self.label_project_name.setObjectName("label_project_name")
        self.gridLayout.addWidget(self.label_project_name, 2, 0, 1, 1)
        self.line_project_name = QtWidgets.QLineEdit(self.centralwidget)
        self.line_project_name.setObjectName("line_project_name")
        self.gridLayout.addWidget(self.line_project_name, 2, 1, 1, 1)
        self.button_load_project = QtWidgets.QPushButton(self.centralwidget)
        self.button_load_project.setObjectName("button_load_project")
        self.gridLayout.addWidget(self.button_load_project, 2, 2, 1, 1)
        self.label_exercise = QtWidgets.QLabel(self.centralwidget)
        self.label_exercise.setObjectName("label_exercise")
        self.gridLayout.addWidget(self.label_exercise, 3, 0, 1, 1)
        self.list_exercises = QtWidgets.QListView(self.centralwidget)
        self.list_exercises.setObjectName("list_exercises")
        self.gridLayout.addWidget(self.list_exercises, 3, 1, 1, 2)
        self.label_selected = QtWidgets.QLabel(self.centralwidget)
        self.label_selected.setObjectName("label_selected")
        self.gridLayout.addWidget(self.label_selected, 4, 0, 1, 1)
        self.line_selected_exercises = QtWidgets.QLineEdit(self.centralwidget)
        self.line_selected_exercises.setObjectName("line_selected_exercises")
        self.gridLayout.addWidget(self.line_selected_exercises, 4, 1, 1, 1)
        self.button_select_exercise = QtWidgets.QPushButton(self.centralwidget)
        self.button_select_exercise.setObjectName("button_select_exercise")
        self.gridLayout.addWidget(self.button_select_exercise, 4, 2, 1, 1)
        self.label_skill_level = QtWidgets.QLabel(self.centralwidget)
        self.label_skill_level.setObjectName("label_skill_level")
        self.gridLayout.addWidget(self.label_skill_level, 5, 0, 1, 1)
        self.group_skill_level = QtWidgets.QGroupBox(self.centralwidget)
        self.group_skill_level.setObjectName("group_skill_level")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_skill_level)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_button_beginner = QtWidgets.QRadioButton(self.group_skill_level)
        self.radio_button_beginner.setObjectName("radio_button_beginner")
        self.horizontalLayout_2.addWidget(self.radio_button_beginner)
        self.radio_button_intermediate = QtWidgets.QRadioButton(self.group_skill_level)
        self.radio_button_intermediate.setObjectName("radio_button_intermediate")
        self.horizontalLayout_2.addWidget(self.radio_button_intermediate)
        self.radio_button_competent = QtWidgets.QRadioButton(self.group_skill_level)
        self.radio_button_competent.setObjectName("radio_button_competent")
        self.horizontalLayout_2.addWidget(self.radio_button_competent)
        self.gridLayout.addWidget(self.group_skill_level, 5, 1, 1, 2)
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setObjectName("button_start")
        self.gridLayout.addWidget(self.button_start, 6, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 286, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_calibrate_projector.setText(_translate("MainWindow", "Calibrate Projector"))
        self.button_init_scene_size.setText(_translate("MainWindow", "Init Scene Size"))
        self.label_exercise_2.setText(_translate("MainWindow", "Exercise type:"))
        self.radio_button_follow.setText(_translate("MainWindow", "Follow The Path"))
        self.radio_button_catch.setText(_translate("MainWindow", "Catch The Object"))
        self.label_project_name.setText(_translate("MainWindow", "Project name:"))
        self.button_load_project.setText(_translate("MainWindow", "Load project"))
        self.label_exercise.setText(_translate("MainWindow", "Exercise:"))
        self.label_selected.setText(_translate("MainWindow", "Selected exercise:"))
        self.button_select_exercise.setText(_translate("MainWindow", "Select"))
        self.label_skill_level.setText(_translate("MainWindow", "Skill level:"))
        self.radio_button_beginner.setText(_translate("MainWindow", "Beginner"))
        self.radio_button_intermediate.setText(_translate("MainWindow", "Intermediate"))
        self.radio_button_competent.setText(_translate("MainWindow", "Competent"))
        self.button_start.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

